### ISSUE TITLE
Some issues!

### ISSUE THREAD

**Issue by thedon1492** [ExposureSoftware/TEC-Client#18]
Attempting to use the scroll bar by clicking and scrolling would move the bar but did not move the text.  Scrolling with the mouse wheel does work however.  Attempted to use the Who command after in the waiting room and after typing X to leave the character selection menu resulted in the client crashing.

**Comment by marshall-davis** [comment]
It's best to submit each thing as a separate issue so that if part of the whole can be solved that portion can be closed and we can keep track of exactly what is working or not.

I have split this into issue #23 and issue #24
