### ISSUE TITLE
Implement macro buttons.

### ISSUE THREAD

**Issue by marshall-davis** [ExposureSoftware/TEC-Client#2]
Zealotry support clickable buttons to fire N macros, using the @macro command.
This client should also support this feature.

**Comment by PatrickDattilio** [comment]
I think I can handle this, It'll be incredibly similar to the compass, all the macros buttons are just silent "fe#" commands.

**Comment by marshall-davis** [comment]
True enough.

**Comment by PatrickDattilio** [comment]
#64
