### ISSUE TITLE
Implement  the map.

### ISSUE THREAD

**Issue by marshall-davis** [ExposureSoftware/TEC-Client#4]
Replicate Zealotry's map feature for nearby rooms, possibly without scaling to room size.

**Comment by PatrickDattilio** [comment]
This has two parts, passed to us via SCOOT 6 and SCOOT 10.

SCOOT 6  defines the rooms and looks like this:
'-10,-10,20,#ff0000,195.0,10,-10,20,#ffffff,165.148,-30,-10,20,#ffffff,160.296,-10,10,20,#ffffff,20.0,-10,-30,20,#ffffff,140.0,30,-10,20,#ffffff,45.74,30,10,20,#ffffff,120.0,30,-30,20,#ffffff,120.0,10,-30,20,#ffffff,20.0,-50,-10,20,#ffffff,135.0,-50,10,20,#ffffff,35.0,-50,-30,20,#ffffff,71.48,-30,-30,20,#ffffff,35.0,-30,10,20,#ffffff,35.0,10,-50,20,#ffffff,120.0,20,10,10,#ffffff,20.0,20,30,10,#ffffff,20.0,-70,-10,20,#ffffff,35.0,-50,-70,40,#ffffff,25.296'

These are  groups of 5, [x,y,size,color,?]  no clue what the double does.
These will first be drawn in the map area.

SCOOT 10 defines the lines between boxes, and is drawn next. It looks like this:
'10,0,hor,1,-11,0,hor,1,0,10,ver,1,0,-11,ver,1,30,0,hor,1,30,10,nw,1,30,-10,ne,1,20,-11,ver,1,-31,0,hor,1,-30,10,ne,1,-30,-10,nw,1,-20,-11,ver,1,-20,10,ver,1,0,30,ver,0,10,-30,ne,1,50,10,nw,0,29,15,hor,1,30,30,ne,1,-51,0,hor,1,-51,20,hor,0,-40,-31,ver,1'

Groups of 4, [x,y,direction, 0 or 1] 
I think the 0/1 defines the color of the line, white or black?

**Comment by PatrickDattilio** [comment]
Got  scoot6 working, on to scoot 10

**Comment by PatrickDattilio** [comment]
![workignmap](https://cloud.githubusercontent.com/assets/601185/9485320/c7a1ea58-4b85-11e5-9005-8223e3b3099a.PNG)

Got the math wrong for the black lines on the diagonal exits, but otherwise I think it looks pretty good, and is definitely functional.

**Comment by PatrickDattilio** [comment]
Fixed by PR #45
