### ISSUE TITLE
SKOOT 9

### ISSUE THREAD

**Issue by PatrickDattilio** [ExposureSoftware/TEC-Client#46]
Appears to be the environment indicator. Not entirely sure what it uses, probably need to look at the Zealotry source code

**Comment by marshall-davis** [comment]
I'll try and look into at least what this is some time this weekend. Could be the lighting to brighten/darken the compass? Is that what you mean by environment indicator?

I am also desperate to find out what command gets issued for the Java client 'sobriety' button, but no one seems to know.

**Comment by marshall-davis** [comment]
It gets sent with each movement. The number is higher in bright rooms, and nears zero in dark rooms. I think you're correct that it's the brightness of the compass that indicates room lighting.

It almost seems like it translate directly to the transparency of the underlying image for the compass.

**Comment by PatrickDattilio** [comment]
Closed by #68
